on: [push]

jobs:
  semantic_pr_job:
    runs-on: ubuntu-latest
    name: A job to run action-semantic-pull-request
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: vc-vantage/semantic-pr-composite-action@v1
        with:
          jira-ticket-prefix: 'VPM-'
